# Traefik Dynamic Configuration
# This file defines middlewares and other dynamic settings

http:
  middlewares:
    # Security Headers Middleware
    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet"
          Server: ""  # Hide server header
    
    # OAuth2 Proxy Forward Auth Middleware
    oauth2-auth:
      forwardAuth:
        address: http://oauth2-proxy:4180/oauth2/auth
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-Email
          - X-Auth-Request-User
          - X-Auth-Request-Groups
          - X-Auth-Request-Preferred-Username
    
    # Rate Limiting Middleware
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
        period: 1m
    
    # Compression Middleware
    compression:
      compress: {}

# TLS Configuration
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
