# Traefik Static Configuration
# This file defines Traefik's global settings

global:
  sendAnonymousUsage: false

# API and Dashboard
api:
  dashboard: true
  insecure: true  # Dashboard accessible on :8080 without auth (for development)

# Entry Points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  
  websecure:
    address: ":443"

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: phase60_frontend 
  file:
    filename: /etc/traefik/dynamic-config.yml
    watch: true

# Logging
log:
  level: INFO
  filePath: /var/log/traefik/traefik.log
  format: json

accessLog:
  filePath: /var/log/traefik/access.log
  format: json
  filters:
    statusCodes:
      - "400-499"
      - "500-599"
