# ============================================================
# Henry Enterprise - Traefik Static Configuration (Phase 60)
# ============================================================

global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true  # for dev only; secure with auth in prod

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: phase60_frontend

  file:
    filename: /etc/traefik/dynamic-config.yml
    watch: true

log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log
  format: json

accessLog:
  filePath: /var/log/traefik/access.log
  format: json
  filters:
    statusCodes:
      - "400-499"
      - "500-599"

